################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= main
# Cuda source files (compiled with cudacc)
CUFILES_sm_11	:= main.cu struct_def.h ExpansionKernel.cu BCPKernel.cu SATCheckingKernel.cu UnitClsKernel.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \

################################################################################
# Rules and targets

include /home/kimura-lab/NVIDIA_GPU_Computing_SDK/C/common/common.mk
